"use client"

import { useEffect, useMemo, useState } from "react"
import { ChevronLeft, ChevronRight, Monitor, X } from "lucide-react"
import type {
  UploadedFile,
  SOAData,
  InvoiceListData,
  OppTrackerData,
  GlobalHopperData,
  ShopVisitData,
  SVRGData,
  CommercialPlanData,
  EmployeeWhereaboutsData,
} from "@/lib/types"
import { ewCategorize } from "@/components/visualizers/employee-whereabouts-visualizer"
import { FILE_TYPE_LABELS } from "@/lib/file-type-meta"
import { fmtMoney, fmtGBP, fmtCount, fmtPct, fmtDays } from "@/lib/format"
import { Button } from "@/components/ui/button"
import { RRWordmark } from "@/components/brand/rr-wordmark"

type SlideKpi = { label: string; value: string; hint?: string }
type Slide = { title: string; subtitle?: string; kpis: SlideKpi[]; bullets: string[] }

function buildSlides(file: UploadedFile): Slide[] {
  const slides: Slide[] = []
  const type = file.file_type

  // 1. Cover slide (common)
  slides.push({
    title: file.name.replace(/\.[^.]+$/, ""),
    subtitle: FILE_TYPE_LABELS[type],
    kpis: [],
    bullets: [
      "Rolls-Royce Civil Aerospace — Finance review",
      "Generated by the Data Visualizer on demand",
      "Use arrows, keyboard or footer controls to navigate",
    ],
  })

  if (type === "SOA") {
    const d = file.parsed as SOAData
    const open =
      d.aging_buckets.current +
      d.aging_buckets["1_30_days"] +
      d.aging_buckets["31_60_days"] +
      d.aging_buckets["61_90_days"] +
      d.aging_buckets["91_180_days"] +
      d.aging_buckets.over_180_days
    const pastDue = open - d.aging_buckets.current
    const topSections = d.sections.slice().sort((a, b) => b.overdue - a.overdue).slice(0, 5)
    slides.push({
      title: "Receivables headlines",
      subtitle: d.metadata.customer_name ?? undefined,
      kpis: [
        { label: "Total open balance", value: fmtMoney(open, "USD") },
        { label: "Total overdue", value: fmtMoney(d.grand_totals.total_overdue, "USD"), hint: open > 0 ? `${fmtPct(pastDue / open)} past due` : undefined },
        { label: "Net balance", value: fmtMoney(d.grand_totals.net_balance, "USD") },
        { label: "Avg days late", value: fmtDays(d.metadata.avg_days_late ?? 0) },
      ],
      bullets: [
        `${d.sections.length} sections analysed across 6 aging buckets`,
        `Worst bucket: ${worstAgingBucket(d)}`,
        `Top overdue section: ${topSections[0]?.name ?? "—"} at ${fmtMoney(topSections[0]?.overdue ?? 0, "USD")}`,
      ],
    })
    slides.push({
      title: "Top overdue sections",
      subtitle: "Ranked by overdue balance",
      kpis: [],
      bullets: topSections.map(
        (s) => `${s.name} — ${fmtMoney(s.overdue, "USD")} overdue (${s.items.length} items)`,
      ),
    })
  }

  if (type === "INVOICE_LIST") {
    const d = file.parsed as InvoiceListData
    const avg = d.totals.item_count > 0 ? d.totals.total_amount / d.totals.item_count : 0
    slides.push({
      title: "Invoice summary",
      subtitle: `Currencies: ${d.metadata.currencies.join(", ")}`,
      kpis: [
        { label: "Total invoiced", value: fmtMoney(d.totals.total_amount, d.metadata.currencies[0] ?? "USD") },
        { label: "Invoices", value: fmtCount(d.totals.item_count) },
        { label: "Average invoice", value: fmtMoney(avg, d.metadata.currencies[0] ?? "USD") },
        { label: "Credits", value: fmtMoney(d.totals.total_negative, d.metadata.currencies[0] ?? "USD") },
      ],
      bullets: [
        `${d.metadata.currencies.length} distinct currencies in register`,
        `${fmtCount(d.totals.item_count)} line items totalling ${fmtMoney(d.totals.total_amount, d.metadata.currencies[0] ?? "USD")}`,
      ],
    })
  }

  if (type === "OPPORTUNITY_TRACKER") {
    const d = file.parsed as OppTrackerData
    const topProg = topEntry(d.summary.by_programme)
    const topCust = topEntry(d.summary.by_customer)
    slides.push({
      title: "Pipeline headlines",
      subtitle: d.metadata.report_title,
      kpis: [
        { label: "Opportunities", value: fmtCount(d.summary.total_opportunities) },
        { label: "Total term benefit", value: fmtGBP(d.summary.total_term_benefit) },
        { label: "Hopper stage", value: fmtCount(d.opportunities_by_level.Hopper.records.length) },
        { label: "Contract stage", value: fmtCount(d.opportunities_by_level.Contract.records.length) },
      ],
      bullets: [
        topProg ? `Top programme: ${topProg[0]} (${fmtCount(topProg[1])} opportunities)` : "—",
        topCust ? `Top customer: ${topCust[0]} (${fmtCount(topCust[1])} opportunities)` : "—",
        `Across ${Object.keys(d.summary.by_customer).length} customers and ${Object.keys(d.summary.by_programme).length} programmes`,
      ],
    })
  }

  if (type === "GLOBAL_HOPPER") {
    const d = file.parsed as GlobalHopperData
    const topRegion = topEntry(d.summary.by_region_value)
    slides.push({
      title: "Hopper portfolio",
      subtitle: d.metadata.title,
      kpis: [
        { label: "Opportunities", value: fmtCount(d.opportunities.length) },
        { label: "CRP term benefit", value: fmtGBP(d.summary.total_crp_term_benefit) },
        { label: "2026 profit", value: fmtGBP(d.summary.total_profit_2026) },
        { label: "2027 profit", value: fmtGBP(d.summary.total_profit_2027) },
      ],
      bullets: [
        topRegion ? `Top region: ${topRegion[0]} — ${fmtGBP(topRegion[1])}` : "—",
        `${d.summary.unique_customers.length} customers across ${d.summary.unique_regions.length} regions`,
        `Pipeline stages: ${d.summary.pipeline_stages.map((s) => `${s.stage} (${s.count})`).join(", ")}`,
      ],
    })
  }

  if (type === "SHOP_VISIT_HISTORY") {
    const d = file.parsed as ShopVisitData
    const topType = topEntry(d.statistics.sv_types)
    const topLoc = topEntry(d.statistics.sv_locations)
    slides.push({
      title: "Shop visit activity",
      subtitle: d.metadata.engine_models.join(", "),
      kpis: [
        { label: "Shop visits", value: fmtCount(d.statistics.total_shop_visits) },
        { label: "Maintenance actions", value: fmtCount(d.statistics.total_maintenance) },
        { label: "Engines tracked", value: fmtCount(d.statistics.total_engines_tracked) },
        { label: "Operators", value: fmtCount(d.metadata.operators.length) },
      ],
      bullets: [
        topType ? `Most common SV type: ${topType[0]} (${fmtCount(topType[1])} visits)` : "—",
        topLoc ? `Top location: ${topLoc[0]} (${fmtCount(topLoc[1])} visits)` : "—",
        `${Object.keys(d.statistics.sv_types).length} SV types across ${Object.keys(d.statistics.sv_locations).length} locations`,
      ],
    })
  }

  if (type === "SVRG_MASTER") {
    const d = file.parsed as SVRGData
    const qualified = d.event_entries.qualifications["Qualified"] ?? 0
    const pending = d.event_entries.qualifications["Pending"] ?? 0
    const nonQualified = d.event_entries.qualifications["Non-Qualified"] ?? 0
    slides.push({
      title: "SVRG exposure",
      subtitle: `${d.metadata.customer} · ${d.metadata.engine_model}`,
      kpis: [
        { label: "Total claims", value: fmtCount(d.claims_summary.total_claims) },
        { label: "Total credit value", value: fmtMoney(d.claims_summary.total_credit_value, "USD") },
        { label: "Total events", value: fmtCount(d.event_entries.total_events) },
        { label: "Qualified", value: fmtCount(qualified) },
      ],
      bullets: [
        `${qualified} qualified events, ${pending} pending, ${nonQualified} non-qualified`,
        `Guarantee coverage across ${Object.keys(d.event_entries.guarantee_types).length} guarantee types`,
        d.claims_summary.claims.length > 0
          ? `Latest claim: ${d.claims_summary.claims[d.claims_summary.claims.length - 1].credit_ref}`
          : "No claims recorded",
      ],
    })
  }

  if (type === "COMMERCIAL_PLAN") {
    const d = file.parsed as CommercialPlanData
    const yearTotals = Object.entries(d.annual_summary.by_year)
      .map(([y, b]) => ({ year: y, total: Number(b.grand_total ?? 0) }))
      .sort((a, b) => a.year.localeCompare(b.year))
    const fiveYearEngines = yearTotals.reduce((s, y) => s + y.total, 0)
    const uniqueCustomers = new Set<string>()
    for (const r of d.one_year_plan.items) if (r.customer) uniqueCustomers.add(String(r.customer).trim())
    for (const r of d.five_year_spe_sales.items) if (r.customer) uniqueCustomers.add(String(r.customer).trim())
    const ownerCounts: Record<string, number> = {}
    for (const r of d.one_year_plan.items) {
      const o = (r.owner || "Unassigned").toString().trim() || "Unassigned"
      ownerCounts[o] = (ownerCounts[o] || 0) + 1
    }
    const topOwner = topEntry(ownerCounts)
    const topCustomerEngines: Record<string, number> = {}
    for (const block of Object.values(d.annual_summary.by_year)) {
      for (const c of block.customers ?? []) {
        topCustomerEngines[c.name] = (topCustomerEngines[c.name] || 0) + (c.total || 0)
      }
    }
    const topCustEng = topEntry(topCustomerEngines)

    slides.push({
      title: `Commercial Plan${d.metadata.plan_year ? ` — ${d.metadata.plan_year}` : ""}`,
      subtitle: d.metadata.sheets_parsed.join(" · "),
      kpis: [
        { label: "1YP actions", value: fmtCount(d.one_year_plan.items.length) },
        { label: "5YP opportunities", value: fmtCount(d.five_year_spe_sales.items.length) },
        { label: "5-year engines", value: fmtCount(fiveYearEngines) },
        { label: "Customers", value: fmtCount(uniqueCustomers.size) },
      ],
      bullets: [
        topCustEng ? `Top customer (5-yr): ${topCustEng[0]} — ${fmtCount(topCustEng[1])} engines` : "—",
        topOwner ? `Top action owner: ${topOwner[0]} (${fmtCount(topOwner[1])} actions)` : "—",
        yearTotals.length > 0
          ? `Year breakdown: ${yearTotals.map((y) => `${y.year} (${fmtCount(y.total)})`).join(", ")}`
          : "No yearly breakdown parsed",
      ],
    })
  }

  if (type === "EMPLOYEE_WHEREABOUTS") {
    const d = file.parsed as EmployeeWhereaboutsData
    let totalEvents = 0
    let holidayEvents = 0
    const byCat: Record<string, number> = {}
    const byCountry: Record<string, number> = {}
    for (const sheet of d.metadata.sheets_parsed ?? []) {
      const rows = d.whereabouts[sheet] ?? []
      for (const row of rows) {
        for (const raw of Object.values(row.daily_status ?? {})) {
          if (raw == null || raw === "") continue
          const cat = ewCategorize(String(raw), d.legend)
          if (!cat) continue
          totalEvents++
          if (cat === "Eid Holiday" || cat === "Other Holidays") holidayEvents++
          byCat[cat] = (byCat[cat] || 0) + 1
          const country = row.country || "Unknown"
          byCountry[country] = (byCountry[country] || 0) + 1
        }
      }
    }
    const topCat = topEntry(byCat)
    const topCountry = topEntry(byCountry)
    const months = d.metadata.months ?? []
    const coverage = months.length
      ? `${months[0]?.start_date ?? "?"} → ${months[months.length - 1]?.end_date ?? "?"}`
      : "—"

    slides.push({
      title: "Workforce coverage",
      subtitle: d.metadata.unique_countries.join(", ") || undefined,
      kpis: [
        { label: "Employees", value: fmtCount(d.metadata.total_employees) },
        { label: "Logged events", value: fmtCount(totalEvents) },
        { label: "Holidays", value: fmtCount(holidayEvents) },
        { label: "Countries", value: fmtCount(d.metadata.unique_countries.length) },
      ],
      bullets: [
        `Coverage window: ${coverage}`,
        topCat ? `Most-logged category: ${topCat[0]} (${fmtCount(topCat[1])} events)` : "—",
        topCountry ? `Most-logged country: ${topCountry[0]} (${fmtCount(topCountry[1])} events)` : "—",
      ],
    })
  }

  // Closing slide
  slides.push({
    title: "Thank you",
    subtitle: "Questions, drill-downs or follow-ups?",
    kpis: [],
    bullets: [
      "Ask the AI Assistant for deeper analysis on any figure",
      "Export this deck to PDF from the header action",
      "Compare this workbook against a previous period in the Compare view",
    ],
  })

  return slides
}

function worstAgingBucket(d: SOAData): string {
  const entries: [string, number][] = [
    ["Current", d.aging_buckets.current],
    ["1–30 days", d.aging_buckets["1_30_days"]],
    ["31–60 days", d.aging_buckets["31_60_days"]],
    ["61–90 days", d.aging_buckets["61_90_days"]],
    ["91–180 days", d.aging_buckets["91_180_days"]],
    ["180+ days", d.aging_buckets.over_180_days],
  ]
  return entries.slice().sort((a, b) => b[1] - a[1])[0]?.[0] ?? "—"
}

function topEntry(obj: Record<string, number>): [string, number] | null {
  const e = Object.entries(obj)
  if (e.length === 0) return null
  return e.sort((a, b) => b[1] - a[1])[0]
}

export function SlidesView({ file }: { file: UploadedFile }) {
  const slides = useMemo(() => buildSlides(file), [file])
  const [index, setIndex] = useState(0)
  const [presenting, setPresenting] = useState(false)

  const current = slides[index]
  const next = () => setIndex((i) => Math.min(i + 1, slides.length - 1))
  const prev = () => setIndex((i) => Math.max(i - 1, 0))

  // Keyboard navigation in presentation mode.
  useEffect(() => {
    if (!presenting) return
    function onKey(e: KeyboardEvent) {
      if (e.key === "ArrowRight" || e.key === "PageDown" || e.key === " ") {
        e.preventDefault()
        next()
      } else if (e.key === "ArrowLeft" || e.key === "PageUp") {
        e.preventDefault()
        prev()
      } else if (e.key === "Escape") {
        setPresenting(false)
      }
    }
    window.addEventListener("keydown", onKey)
    return () => window.removeEventListener("keydown", onKey)
  }, [presenting])

  // Reset index when switching file.
  useEffect(() => {
    setIndex(0)
  }, [file.name])

  return (
    <div className={presenting ? "fixed inset-0 z-50 bg-[#0b1a2e] text-white flex flex-col" : "p-6 lg:p-8 space-y-4"}>
      {!presenting && (
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-semibold tracking-tight text-foreground font-display">
              Slideshow
            </h1>
            <p className="mt-1 text-sm text-muted-foreground">
              Auto-generated executive deck from {file.name}.
            </p>
          </div>
          <Button onClick={() => setPresenting(true)} className="gap-2">
            <Monitor className="h-4 w-4" />
            Present
          </Button>
        </div>
      )}

      <div
        className={
          presenting
            ? "flex-1 min-h-0 flex flex-col justify-center items-center px-10"
            : "aspect-[16/9] w-full max-w-5xl mx-auto rounded-xl border border-border bg-[#0b1a2e] text-white p-10 shadow-lg overflow-hidden flex flex-col"
        }
      >
        <div className="flex items-center justify-between w-full">
          <RRWordmark className="text-white" tone="light" />
          <div className="text-[11px] uppercase tracking-[0.2em] text-white/60">
            Civil Aerospace &middot; Finance
          </div>
        </div>

        <div className="flex-1 flex flex-col justify-center mt-8 w-full max-w-4xl mx-auto">
          {current.subtitle && (
            <div className="text-[11px] uppercase tracking-[0.2em] text-[#c9a55a] font-semibold mb-3">
              {current.subtitle}
            </div>
          )}
          <h2
            className={
              presenting
                ? "text-5xl lg:text-6xl font-semibold tracking-tight font-display text-white text-balance"
                : "text-3xl lg:text-4xl font-semibold tracking-tight font-display text-white text-balance"
            }
          >
            {current.title}
          </h2>

          {current.kpis.length > 0 && (
            <div className="mt-8 grid grid-cols-2 lg:grid-cols-4 gap-4">
              {current.kpis.map((k) => (
                <div
                  key={k.label}
                  className="rounded-lg border border-white/10 bg-white/[0.03] p-4"
                >
                  <div className="text-[10px] uppercase tracking-wider text-white/60">{k.label}</div>
                  <div className="mt-2 font-mono tabular-nums text-2xl font-semibold text-white">
                    {k.value}
                  </div>
                  {k.hint && <div className="mt-1 text-xs text-white/50">{k.hint}</div>}
                </div>
              ))}
            </div>
          )}

          {current.bullets.length > 0 && (
            <ul className="mt-8 space-y-3">
              {current.bullets.map((b, i) => (
                <li key={i} className="flex gap-3 text-base lg:text-lg text-white/85 leading-relaxed">
                  <span className="text-[#c9a55a] mt-1">—</span>
                  <span className="text-pretty">{b}</span>
                </li>
              ))}
            </ul>
          )}
        </div>

        <div className="flex items-center justify-between w-full mt-6 pt-6 border-t border-white/10">
          <div className="text-xs text-white/50 tabular-nums">
            {index + 1} / {slides.length}
          </div>
          <div className="flex items-center gap-2">
            <Button
              size="sm"
              variant="outline"
              onClick={prev}
              disabled={index === 0}
              className="bg-transparent border-white/20 text-white hover:bg-white/10 hover:text-white"
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <Button
              size="sm"
              variant="outline"
              onClick={next}
              disabled={index === slides.length - 1}
              className="bg-transparent border-white/20 text-white hover:bg-white/10 hover:text-white"
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
            {presenting && (
              <Button
                size="sm"
                variant="outline"
                onClick={() => setPresenting(false)}
                className="bg-transparent border-white/20 text-white hover:bg-white/10 hover:text-white gap-1"
              >
                <X className="h-4 w-4" />
                Exit
              </Button>
            )}
          </div>
        </div>
      </div>

      {!presenting && (
        <div className="max-w-5xl mx-auto w-full">
          <div className="flex flex-wrap gap-2">
            {slides.map((s, i) => (
              <button
                key={i}
                onClick={() => setIndex(i)}
                className={`rounded-md border px-3 py-1.5 text-xs font-medium transition ${
                  i === index
                    ? "border-primary bg-primary text-primary-foreground"
                    : "border-border bg-background text-muted-foreground hover:text-foreground hover:border-ring"
                }`}
              >
                {i + 1}. {s.title}
              </button>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
